"""empty message

Revision ID: d773119f6e29
Revises: 3679caf6e0bd
Create Date: 2021-05-18 17:40:33.323995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd773119f6e29'
down_revision = '3679caf6e0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=225), nullable=True))
    op.create_unique_constraint('uq_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
